#!/bin/bash

echo "Создаем файлы в директориях"
# $1=место расположения папок
# $2=количество папок а
# $3=количество папок b
# $4=количество папок c
# $5=шаблон имени
cd $1
for ((a = 1; a <= $2; a++))
do
mkdir $5A$a
cd $5A$a
 for ((b = 1; b <= $3; b++))
 do
 mkdir $5B$b
  cd $5B$b
     for ((c = 1; c <= $4; c++))
     do 
     touch textС$c.txt
     done
  cd ..		
 done
cd ..
done

ls
